name: apexburn
description: A modern compiler for multiple languages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.2.4  # Add this for file picking capability
  path_provider: ^2.0.14  # Add this for path management
